---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-ping
  namespace: monitoring
  labels:
    tier: monitoring
    app: node-ping
    version: v1
spec:
  selector:
    matchLabels:
      name: node-ping
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: node-ping
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 0
      tolerations:
      - operator: "Exists"
      serviceAccountName: node-ping
      containers:
      - image: atalabirchuk/fpinger-main:latest
        imagePullPolicy: Always
        name: node-ping
        # args: ["-b", "1000"] example use args
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONFIG_PATH
            value: "/config/targets.json"
          - name: PROMETHEUS_TEXTFILE_DIR
            value: "/node-exporter-textfile/"
          - name: PROMETHEUS_TEXTFILE_PREFIX
            value: "monitoring-ping_"
        volumeMounts:
          - name: textfile
            mountPath: /node-exporter-textfile
          - name: config
            mountPath: /config
      - resources:
          requests:
            cpu: 0.10
      volumes:
        - name: textfile
          hostPath:
            path: /var/run/node-exporter-textfile
        - name: config
          configMap:
            name: node-ping-config