{
 "title": "Nodes ping",
 "tags": [ "nodes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "env",
    "query": {
     "query": "label_values(kube_node_ping_packets_sent_total, env)"
    }
   },
   {
    "name": "source_node",
    "label": "Source",
    "query": {
     "query": "label_values(kube_node_ping_packets_sent_total{env=\"$env\"}, instance)"
    }
   },
   {
    "name": "destination_node",
    "label": "Destination",
    "query": {
     "query": "label_values(kube_node_ping_packets_sent_total{env=\"$env\"}, destination_node_ip_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "From all nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table-old",
   "description": "Average measurement values grouped by ping request targets",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\",env=\"$env\"}[$__range]))\n  -\n  sum by (destination_node) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\",env=\"$env\"}[$__range]))\n)\n/\n  sum by (destination_node) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\",env=\"$env\"}[$__range]))"
    },
    {
     "expr": "sum by (destination_node) (increase(kube_node_ping_rtt_milliseconds_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\",env=\"$env\"}[$__range]))\n/\nsum by (destination_node) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\",env=\"$env\"}[$__range]))"
    },
    {
     "expr": "avg by (destination_node) (avg_over_time(kube_node_ping_rtt_mdev{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\",env=\"$env\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average mean RTT with min/max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n/\nsum (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "RTT"
    },
    {
     "expr": "max (max_over_time(kube_node_ping_rtt_max{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "RTT max"
    },
    {
     "expr": "min (min_over_time(kube_node_ping_rtt_min{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "RTT min"
    }
   ]
  },
  {
   "title": "Mean packet loss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( \n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n  -\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n)\n/\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mean RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_node_ip_address) (increase(kube_node_ping_rtt_milliseconds_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n/\nsum by (destination_node_ip_address) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mean deviation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (destination_node_ip_address) (avg_over_time(kube_node_ping_rtt_mdev{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "From $source_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "source_node",
   "targets": [
    {}
   ]
  },
  {
   "type": "table-old",
   "description": "Average measurement values grouped by ping request sources",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[$__range]))\n  -\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[$__range]))\n)\n/\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[$__range]))"
    },
    {
     "expr": "sum by (destination_node_ip_address) (increase(kube_node_ping_rtt_milliseconds_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n/\nsum by (destination_node_ip_address) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))"
    },
    {
     "expr": "avg by (destination_node_ip_address) (avg_over_time(kube_node_ping_rtt_mdev{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average mean RTT with min/max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (increase(kube_node_ping_rtt_milliseconds_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n/\nsum (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "RTT"
    },
    {
     "expr": "max (max_over_time(kube_node_ping_rtt_max{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "RTT max"
    },
    {
     "expr": "min (min_over_time(kube_node_ping_rtt_min{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "RTT min"
    }
   ]
  },
  {
   "title": "Mean packet loss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n  -\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n)\n/\n  sum by (destination_node_ip_address) (increase(kube_node_ping_packets_sent_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mean RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_node_ip_address) (increase(kube_node_ping_rtt_milliseconds_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))\n/\nsum by (destination_node_ip_address) (increase(kube_node_ping_packets_received_total{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  },
  {
   "title": "Mean deviation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (destination_node_ip_address) (avg_over_time(kube_node_ping_rtt_mdev{instance=~\"$source_node\", destination_node_ip_address=~\"$destination_node\"}[5m]))",
     "legendFormat": "{{destination_node}}"
    }
   ]
  }
 ]
}